import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu,ExternalLink} from 'lucide-react';
import '@fontsource/ibm-plex-sans/latin-400.css';
import '@fontsource/ibm-plex-sans/latin-600.css';
import '@fontsource/jetbrains-mono/latin-400.css';
import Navigation from './Navigation';import Home from './Home';import Reader from './Reader';import Library from './Library';import About from './About';
import {documents,manifest} from './content';import {useRoute,useStored} from './state';import './styles.css';
function App(){
 const rawRoute=useRoute(),route=rawRoute.split('?')[0];
 const [query,setQuery]=useState(''),[open,setOpen]=useState(false),[completed,setCompleted]=useStored('modding-kompass.completed',[]),[resetting,setResetting]=useState(false);
 const doc=documents.find(d=>d.id===route);
 useEffect(()=>{setOpen(false);document.title=`${doc?.title||'Modding Kompass'} – Modding Kompass`;if(!rawRoute.includes('anchor='))window.scrollTo({top:0,behavior:'instant'});},[rawRoute]);
 useEffect(()=>{const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();location.hash='/suche';setOpen(false);setTimeout(()=>document.querySelector('.library-search input')?.focus(),50);}if(e.key==='Escape'){setOpen(false);setResetting(false);}if(e.key==='Tab'&&resetting){const buttons=[...document.querySelectorAll('.modal button')];if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0]?.focus();}}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[resetting]);
 function toggle(id){setCompleted(previous=>previous.includes(id)?previous.filter(x=>x!==id):[...previous,id]);}
 function reset(){setResetting(true);}
 return <><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content').focus();}}>Zum Inhalt springen</a><Navigation route={route} query={query} setQuery={setQuery} completed={completed} open={open} close={()=>setOpen(false)}/><main id="main-content" tabIndex={-1}><header className="topbar"><button className="menu-button" aria-expanded={open} aria-label="Kapitelmenü öffnen" onClick={()=>setOpen(true)}><Menu size={23}/></button><div className="breadcrumb"><a href="#/start">Lernpfad</a><span>/</span><span>{doc?.title||({start:'Einstieg',kapitel:'Alle Kapitel',vorlagen:'Vorlagen',suche:'Suche',ueber:'Über diese Ausgabe'}[route]||'Seite nicht gefunden')}</span></div><a className="original-link" href={doc?.source||manifest.upstream} target="_blank" rel="noopener noreferrer">Englisches Original<ExternalLink size={16}/></a></header><div className="content-wrap">{doc?<Reader key={doc.id} doc={doc} completed={completed} toggleCompleted={toggle}/>:route==='start'?<Home/>:['kapitel','vorlagen','suche'].includes(route)?<Library kind={route} query={query} setQuery={setQuery} completed={completed}/>:route==='ueber'?<About reset={reset}/>:<><h1>Diese Seite gibt es nicht.</h1><a className="button primary" href="#/kapitel">Alle Kapitel öffnen</a></>}</div><footer className="app-footer">Deutsche Bearbeitung der <a href={manifest.upstream} target="_blank" rel="noopener noreferrer">AI Game Modding Guides</a> · Original: Trev & Mitwirkende · MIT</footer></main>{resetting&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><h2 id="reset-title">Lesefortschritt zurücksetzen?</h2><p>Abgeschlossene Kapitel, Lesepositionen und abgehakte Checklisten werden in diesem Browser zurückgesetzt.</p><div><button autoFocus className="button quiet" onClick={()=>setResetting(false)}>Abbrechen</button><button className="button primary" onClick={()=>{setCompleted([]);try{for(const key of Object.keys(localStorage)){if(key==='modding-kompass.positions'||key.startsWith('modding-kompass.task.'))localStorage.removeItem(key);}}catch{}setResetting(false);}}>Zurücksetzen</button></div></div></div>}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
